<!DOCTYPE html>
<html>
<head>
	<title>Menu Makanan</title>
</head>
<body background="c.webp">
	<h1 text align="center"> SELAMAT DATANG DI ANTEIKU COFFEE </h1>
	<h2>Saya Septa Nanda, selaku owner Anteiku beralamat di Perumahan Asabri bumiayu Indah C5.
	Saya lahir di Malang, kemudian saya mencoba mengembangkan sebuah kedai kopi yang nyaman dan dapat menjadi tempat berkumpul para anak muda untuk saling bercengkrama</h2>
	<p><h2>Kedai kopi ini bertemakan anak muda yang kreatif dan milenialis, sehingga kami mendesign kedai kopi ini sekreatif mungkin dan tidak adanya unsur mainstream</h2></p>
	<br><br>
	<center><img src="custard.jpg" height="150" width="200"><center>
	<img src="ice.jpg" height="150" width="200">
	<img src="oreo.jpg" height="150" width="200">
	<img src="cappuccino.jpg" height="150" width="200">
	<img src="cheese.jpg" height="150" width="200">
	<img src="expresso.jpg" height="150" width="200">
	<img src="macchiato.jpg" height="150" width="200">
	<br><br>
	<h3>Klik <a href="4.html">Disini</a> untuk memesan</h3>
	<br>
	<h2>Menu Dessert:</h2>
	<table border="1" cellpadding="10">
        <tr>
            <td bgcolor="#E0FFFF">Dessert</td>
            <td bgcolor="#E0FFFF">Harga</td>
        </tr>
        <tr>
            <td>Cheese Cake</td>
            <td>30.000</td>
        </tr>
        <tr>
            <td>Custard Pudding</td>
            <td>25.000</td>
        </tr>
        <tr>
            <td>Ice Cream Crepes</td>
            <td>25.000</td>
        </tr>
        <tr>
            <td>White Oreo</td>
            <td>20.000</td>
        </tr>
        <tr>
            <td>Souffle Leger</td>
            <td>35.000</td>
        </tr>
        <tr>
            <td>Manggo Pancake</td>
            <td>20.000</td>
        </tr>
    </table>
   
    </table>
    <h2>Menu Minuman:</h2>
    <table border="1" cellpadding="10">
        <tr>
            <td bgcolor="#E0FFFF">Minuman</td>
            <td bgcolor="#E0FFFF">Harga</td>
        </tr>
        <tr>
            <td>Expresso</td>
            <td>15.000</td>
        </tr>
        <tr>
            <td>Ristretto</td>
            <td>18.000</td>
        </tr>
        <tr>
            <td>Cappuccino</td>
            <td>25.000</td>
        </tr>
        <tr>
            <td>Macchiato</td>
            <td>20.000</td>
        </tr>
        <tr>
            <td>Cortado</td>
            <td>20.000</td>
        </tr>
        <tr>
            <td>Latte</td>
            <td>25.000</td>
        </tr>
    </table>
    <br><br><br>
	<marquee><h2>Follow Instagram kami <font color="navy">@anteikucoffe</font>
</body>
</html>