<!DOCTYPE html>
<html>
<head>
	<title text align="center">RUMAH MAKAN</title>
</head>
<body background="c.webp">
	<h1 text align="center"> SELAMAT DATANG DI ANTEIKU COFFEE </h1>
	<br><br>
	<h2 text align="center">Tersedia berbagai macam Dessert dan Coffee yang LIFT UP YOUR MOOD</h2>
	<h2 text align="center">Diskon tersedia untuk pengguna <font color="navy">member</font></h2>
	<h2 text align="center">Jadi silahkan gabung untuk menjadi member dan nikmati diskon kami </h2>
	<center><img src="anteiku.jpg" height="300" width="300"><center>
	<br><br><br>
	<a href="2.html"><h3>Klik Untuk Melanjutkan</h3></a>
	<br><br><br>
	<marquee><h2>Follow Instagram kami <font color="navy">@anteikucoffe</font> 
</body>
</html>